<?php 
$this->headLink()->appendStylesheet("//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.css");
$this->inlineScript()->appendFile("//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js");
$this->inlineScript()->appendFile("//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js");
?>
<h2>Liste des utilisateurs</h2>
<hr />
<a href="<?= $this->url(array(), 'userAdd')?>" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-plus"></span> Nouvel utilisateur</a>
<hr />

<?= count($this->messages) ? '<p>' . implode('<br />',$this->messages) . '</p>' : '' ?>

<table id="users" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user) :?>
        <tr>
            <td><?= $user->getId()?></td>
            <td><?= $user->getName()?></td>
            <td><a href="<?= $this->url(array('id' => $user->getId()), 'userEdit')?>" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-pencil"></span> Editer</a>
                <a href="<?= $this->url(array('id' => $user->getId()), 'userDelete')?>" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span> Supprimer</a></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>
    
<script>
<?php $this->inlineScript()->captureStart() ?>
$(document).ready(function() {
	$('#users').dataTable();
} );
<?php $this->inlineScript()->captureEnd() ?>
</script>