<?php
    $this->headLink()->appendStylesheet("/assets/datatables/media/css/jquery.dataTables.css"); 
    //$this->headStyle()->appendStyle('td, th, a{color:black;');
    ob_start();
?>
td, th {
    color: black;
}

div#welcome {
	color: #FFFFFF;
	background-image: url(http://framework.zend.com/images/bkg_header.jpg);
	width: 600px;
	border: 2px solid #444444;
	overflow: hidden;
}
<?php 
    $style = ob_get_clean();
    $this->headStyle()->appendStyle($style);
?>

                <div id="welcome">
                    <table id="table_id" class="display">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Password</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Password</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>                
                        <tbody>
        <?php 
            foreach($this->users as $user){?>
                            <tr>
                                <td><?= $user->getId();?></td>
                                <td><?= $user->getName();?></td>
                                <td><?= $user->getPassword();?></td>
                                <td><a href="/user/delete?id=<?= $user->getId();?>" class="btn btn-danger">Supprimer</a></td>
                                <td><a href="/user/update?id=<?= $user->getId();?>" class="btn btn-danger">Modifier</a></td>
                            </tr>
        <?php 
            }
        ?>
                        </tbody>        
                    </table>
                </div>

<?php $this->inlineScript()->appendFile("/assets/datatables/media/js/jquery.dataTables.js");?>

<?php 
ob_start(); ?>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
<?php 
    $script = ob_get_clean(); 
    $this->inlineScript()->appendScript($script);
?>