<?php $this->headLink()->appendStylesheet("/css/zf.css");?>
<div id="welcome">
	<form role="form" method="post" action=/user/save>
		<fieldset>

			<!-- Form Name -->
			<legend>Modification d'un utilisateur</legend>
			
			<!-- Hidden input-->
            <input id="id" name="id" type="hidden" class="form-control" value="<?= $this->user->getId();?>">
			
			<!-- Text input-->
			<div class="form-group">
				<label for="name">Nom</label>
                <input id="name" name="name" type="text" class="form-control" value="<?= $this->user->getName();?>">
			</div>

			<!-- Password input-->
			<div class="form-group">
				<label for="password">Mot de passe</label>
                <input id="password" name="password" type="password" class="form-control" value="<?= $this->user->getPassword();?>">
			</div>

			<!-- Button (Double) -->
			<div class="form-group">
				<label for="save"></label>
				<button id="save" name="save" class="btn btn-success">Enregistrer</button>
				<a href = "/user/read" class="btn btn-danger">Annuler</a>
			</div>

		</fieldset>
	</form>

</div>